name: Release_v2

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      -
        name: Installing npm modules
        run: npm install
      -
        name: Build components
        run: npm run build
      -
        name: Create Changelog and bump release version
        uses: labor-digital/conventional-release-action@master
        with:
          github-token: ${{ secrets.github_token }}
      -
        name: Publish library on npm
        run: npm publish --provenance --access public
